name: Tripla Terraform CI/CD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  TF_VERSION: 1.12.2

jobs:
  terraform-validate-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [ ap-southeast-1, ap-northeast-3 ]
    defaults:
      run:
        working-directory: ./${{ matrix.region }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Set AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ matrix.region }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -out=tfplan-${{ matrix.region }}.bin

      - name: Show Plan Summary
        run: terraform show -no-color tfplan-${{ matrix.region }}.bin

  terraform-apply:
    name: "Terraform Apply"
    if: github.ref == 'refs/heads/main'
    needs: terraform-validate-plan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [ ap-southeast-1, ap-northeast-3 ]
    defaults:
      run:
        working-directory: ./${{ matrix.region }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Set AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ matrix.region }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -out=tfplan-${{ matrix.region }}.bin

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan-${{ matrix.region }}.bin
